### ISSUE TITLE
Figure 4

### ISSUE THREAD

**Issue by laurenmh** [laurenmh/NWT_renewal#1]
Figure 4: 1/3 page. Stacked panels showing response in GL4 chl A, saddle vegetation grid, pika survival, NEE, along common time axis. Add analysis of temporal synchrony on the variables in the figure: [Emily, Lauren, Caitlin]
- ChA: Need to determine best aggregate for chlorophyll A (average after stratification? average by year?), Caitilin
- Pika survival, Caitlin

-NEE: Use data from John's paper?, Emily

-Productivity, Emily
- Vegetation, Lauren

General issue might be to ensure there is enough yearly overlap to compare among the figures

**Comment by laurenmh** [comment]
Lake data is 2000-2014 (from Katya), and more on the NWT website, but a little messier

**Comment by caitlintwhite** [comment]
This issue has been resolved, Figure 4 assembled-- has 4 panels: pika weights, max chl-a, mean NO3, and ANPP, all plotted against PC1.
